name: garbagecan
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  geolocator: ^6.1.13
  geocoder: ^0.2.1
  table_calendar: ^2.3.3
  provider: ^4.3.2+3
  intl: ^0.16.1
  flutter_datetime_picker: ^1.4.0
  modal_progress_hud: ^0.1.3
  awesome_dialog: ^1.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        


  
